ALTER TYPE "RunJobStatus" ADD VALUE IF NOT EXISTS 'SCANNING';
ALTER TYPE "RunJobStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';

ALTER TABLE "run_jobs"
ADD COLUMN "scan_report" JSONB,
ADD COLUMN "run_policy" JSONB,
ADD COLUMN "log_stats" JSONB;